spring:
  application:
    name: user-management-service

server:
  port: 8090

keycloak:
  realm: master
  server-url: http://localhost:8086
  client-id: admin-cli
  admin-username: admin
  admin-password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}