server:
  port: 8082

spring:
  application:
    name: redirect-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# For Feign Load Balancing (if you still have WebClient base-url, you can remove it)
# ⚠️ Important: remove this when using Feign with Eureka
# url-shortener:
#   base-url: http://localhost:8081
resilience4j:
  retry:
    instances:
      shortenerRetry:
        maxAttempts: 3
        waitDuration: 1s

  circuitbreaker:
    instances:
      shortenerCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
