server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: url-shortner-service
          uri: lb://url-shortner-service
          predicates:
            - Path=/shorten/**
          filters:
            - RewritePath=/shorten/(?<segment>.*), /shorten/${segment}
          # optional: add filters later for security

        - id: redirect-service
          uri: lb://redirect-service
          predicates:
            - Path=/redirect/**
#          filters:
#            - RemoveRequestHeader=Authorization

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:

    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: Vw3eX5g9Jz4pQ7sYv9rL2eJb3nT6yB1w
  expiration: 86400000 # 1 day in milliseconds
