server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: url-shortner-service
          uri: lb://url-shortner-service
          predicates:
            - Path=/shorten/**
          filters:
            - RewritePath=/shorten/(?<segment>.*), /shorten/${segment}

        - id: redirect-service
          uri: lb://redirect-service
          predicates:
            - Path=/redirect/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**

        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: Vw3eX5g9Jz4pQ7sYv9rL2eJb3nT6yB1w
  expiration: 86400000 # 1 day in milliseconds

keycloak:
  public-key: >
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzP7HXIyscqdOjHGes4tRnN2jQas3s3PfLe9hnsyeY6lWqE7U9rPSyRPfIyDrP6ipZA8OLdrj3Rt9z6xNg2EtwMtqyYjAaA9hj4LHvLTi/EpUEmES9Zn/r86gKmxsOguw9kI7FYPya1K5zY1xy1XdT17nJQ3oraADqdCxxMv20v35xgei0h3Ossr87oVJAxW4NiMbNS0MrD+WxwLAqQJDigoJp/1eihpNpZpkCaZQbyqdC0/d9EvbCtvR8mlXCEZ87iyPEyHam4/Rzgpd+a+fn/melShqKSbcoLTjgzp8YSs6gkAen+pauJSr89QDl6rr3an3luXfIitzeTRSPVvCXQIDAQAB